DEBUG = True
# 打印sql语句
SQLALCHEMY_ECHO = True

SQLALCHEMY_DATABASE_URI = 'mysql://root:123456@127.0.0.1/food_db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = 'utf-8'
AUTH_COOKIE_NAME = 'mooc_food'